GET http://localhost:8000/refresh
Content-Type: application/json
Set-Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBoYXR2dSIsImlhdCI6MTY4NDg2MDI1NywiZXhwIjoxNjg0ODYwMjc3fQ.rzXWU4D96-lCX9i1M7qmmiAnOa27hT_T1zDrrGGZfW4; Max-Age=60; Path=/; Expires=Tue, 23 May 2023 16:45:17 GMT; HttpOnly; SameSite=None
